---
title: "a4_results_b"
author: "Qusai Bhaijeewala"
date: "11/8/2019"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
#attaching packages

library(tidyverse)
library(janitor)
```


```{r}

# read in spiny lobster data

lob_abun <- read_csv("lobster_abundance_sbc_lter.csv", 
                    na = "-99999") %>% 
  clean_names()


```


```{r}

# data structure: each site has several transects, and within each transect they have either A, B, C, or D replicates. The count column can has multiple counts of the same transect number and replicate, we want to make each of those counts a seperate row.

# uncount lobsters so each lobster has its own row
lob_tidy <- lob_abun %>% 
  tidyr::uncount(count)

```



```{r}


# filtering years of 2012 and 2018 only

lob_size <- lob_tidy %>% 
  filter(year %in% c(2012,2018))

ggplot(lob_size, aes(x = size_mm)) +
  geom_histogram(aes(fill = site)) +
  facet_grid(site ~ year, scales = "free_y") +
  theme_light() +
    labs(x = "Lobster size (mm)", y = "Lobster Count", 
       title = "Lobster size distributions observed at the 5 different sites \n in 2012 and 2018")
 # theme_update(plot.title = element_text(hjust = 0.5)) +
  #geom_hline(yintercept = 6377, color = "blue")
 # annotate(geom = "text",
           #x = 1940, y = 6380,
          # label = "Land Bridges Emerge",
          # color = "black") +
 # geom_point(x = 1941, y = 6417, color = "red", size = 2) +
 # annotate("segment", x = 1960, y = 6426, xend = 1941, yend = 6417,
#           size = 0.5, arrow = arrow(), color = "red") +
#  annotate(geom = "text",
          # x = 1970, y = 6429,
          # label = "Mono Basin Diversions Begin",
         #  color = "black", size = 4) +
  #geom_ribbon(aes(ymin = 6370, ymax = lake_level_feet_above_sea_level,
  ##                color = "Light Blue", alpha = .5),
  #            show.legend = FALSE)

```


```{r}
ggplot(lob_size, aes(x = site, y = size_mm)) +
  geom_jitter(aes(color = site)) +
  facet_wrap(~year) +
  theme_dark() +
    labs(x = "site", y = "Lobster size (mm)", 
       title = "Lobster size distributions observed at the 5 different sites \n in 2012 and 2018")
 # theme_update(plot.title = element_text(hjust = 0.5)) +
  #geom_hline(yintercept = 6377, color = "blue")
 # annotate(geom = "text",
           #x = 1940, y = 6380,
          # label = "Land Bridges Emerge",
          # color = "black") +
 # geom_point(x = 1941, y = 6417, color = "red", size = 2) +
 # annotate("segment", x = 1960, y = 6426, xend = 1941, yend = 6417,
#           size = 0.5, arrow = arrow(), color = "red") +
#  annotate(geom = "text",
          # x = 1970, y = 6429,
          # label = "Mono Basin Diversions Begin",
         #  color = "black", size = 4) +
  #geom_ribbon(aes(ymin = 6370, ymax = lake_level_feet_above_sea_level,
  ##                color = "Light Blue", alpha = .5),
  #            show.legend = FALSE)


```

