---
title: "206 A4 Result A"
author: "Ruiheng Jin"
date: "11/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
library(tidyverse)
library(janitor)
lob_abun <- read_csv("lobster_abundance_sbc_lter.csv",
                     na = "-99999") %>% 
  clean_names()

```




### RESULTS A: CHANGES IN ANNUAL LOBSTER ABUNDANCE AT FIVE SITES

```{r}
# data structure: each site has several transects, each transect has ABCD replicates

# uncount lobsters so each lobster has its own row
lob_tidy <- lob_abun %>% 
  tidyr::uncount(count)
```

```{r}
# count total lobster count by year and site
lob_yr_site <- lob_tidy %>%
  count(year, site)

# make a line graph of abundance change through the years

## option 1
#ggplot(lob_yr_site, aes(x = year, y = n, color = site)) +
#  geom_line(size = .5) +
#  geom_point()

## option 2
lob_yr_site$site2 <- factor(lob_yr_site$site, labels = c("Arroyo Quemado", "Carpinteria", "Isla Vista", "Mohawk", "Naples"))

ggplot(lob_yr_site, aes(x = year, y = n)) +
  facet_wrap(~site2) +
  geom_line(color = "#b62b2b", size = 1) +
  geom_point(color = "#4b1313", size = 2) +
  labs(x = "", 
       y = "Lobster abundance", 
       title = "Lobster Abundance at Five Sites (2012-2018)",
       caption = "Figure 1. Lobster abundance from 5 study sites, from year 2012 to 2018.") +
  scale_x_continuous(expand = expand_scale(add = c(1, 1)),
                     breaks = c(2012, 2014, 2016, 2018)) +
  scale_y_continuous(expand = expand_scale(add = c(0, 0)),
                     limits = c(0, 1000)) +
  theme_light() +
  theme(plot.caption = element_text(hjust = 0, size = 10),
        title = element_text(size = 13)) 
# NEED TO FIGURE OUT HOW TO INCREASE GAP BETWEEN  
  
  
# geom_col(position = 'dodge') 
```

At all sites but Arroyo Quemado, there is a general increase in lobster abundance; Carpinteria and Isla Vista have significantly larger rates of increase than the rest.












